Repository MLB-FPL/MLB-backend, pull requests merged in 2025-08, with the labels that each got.

#22 RedisConfig.java 관련 수정
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/controller/DraftController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/redis/RedisConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/redis/RedisConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/redis/RedisPublisher.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/redis/RedisSubscriber.java
Labels: enhancement

#26 Feat/#18 채팅 모듈 통합 및 기능 추가 + security 설정 수정
  backendProject/.env.example
  backendProject/build.gradle
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatPresenceController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatRestController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatRoomController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/ChatRoomDto.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/PresenceDto.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/ChatMessageDocument.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/ChatMessageSearchRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/event/ChatMessageEvent.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/event/ChatMessageIndexer.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/repository/ChatMessageRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/repository/ChatRoomRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/ChatRoomService.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/ChatService.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatRoomServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/match/dto/RoundInfo.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/match/repository/ParticipantRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/ElasticsearchConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/KafkaConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/WebSocketConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/runner/FplDataLoader.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/runner/dto/bootstrap/FplEvent.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/security/config/SecurityConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/security/oauth/CustomOAuth2UserService.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/staticdata/entity/Fixture.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/staticdata/entity/Round.java
  backendProject/src/main/resources/elasticsearch/chat-messages/mappings.json
  backendProject/src/main/resources/elasticsearch/chat-messages/settings.json
  docker-compose.yml
Labels: enhancement

#38 hotfix 토큰 부분 변경 #37
  backendProject/src/main/java/likelion/mlb/backendProject/global/security/jwt/JwtTokenProvider.java
Labels: bug

#41 feat: 채팅/알림 백엔드 안정화: 메시지 파이프라인 단일화(Kafka), SYSTEM/ALERT 색인, STOMP 권한 강화, Presence 입·퇴장 추가
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatPresenceController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatPresenceRestController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatPresenceStompController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/ChatMessageDto.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/ChatPresenceResponse.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/PresenceDto.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/entity/ChatMessage.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/event/ChatMessageIndexer.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/repository/ChatRoomRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/ChatNotificationService.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/ChatPresenceService.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatNotificationServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatPresenceServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatRoomServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/repository/DraftRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/WebSocketConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/exception/ErrorCode.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/scheduler/LiveDataScheduler.java
Labels: enhancement

#45 hotfix securityconfig 부분 변경 #37
  backendProject/src/main/java/likelion/mlb/backendProject/global/security/config/SecurityConfig.java
Labels: bug

#55 feat/ 배포를 위한 docker 파일들 변경 및 추가
  backendProject/Dockerfile
  docker-compose.yml
Labels: enhancement

#61 배포를 위한 docker-compose 파일 추가 및 securityConfig 수정, deploy 파일 추가
  .github/workflows/deploy.yml
  backendProject/src/main/java/likelion/mlb/backendProject/global/health/HealthController.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/security/config/SecurityConfig.java
  docker-compose-prod.yml
Labels: enhancement

#83 deploy 테스트
  .github/workflows/deploy.yml
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/controller/DraftController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/dto/DraftParticipant.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/service/DraftService.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/match/entity/Participant.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/dto/ElementTypeDto.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/entity/ElementType.java
Labels: enhancement

#85 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#86 deploy 파일 테스트
  .github/workflows/deploy.yml
Labels: bug

#88 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#91 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#94 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#97 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#98 deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#101 deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#104 deploy 수정수정
  .github/workflows/deploy.yml
Labels: bug

#106 hotfix - deploy 수정
  .github/workflows/deploy.yml
Labels: bug

#109 hotfix - docker 관련 수정
  backendProject/Dockerfile
  docker-compose-prod.yml
Labels: bug

#110 docker 관련 수정
  backendProject/Dockerfile
  docker-compose-prod.yml
Labels: bug

#112 hotfix - docker 관련 수정
  .github/workflows/deploy.yml
  backendProject/Dockerfile
  docker-compose-prod.yml
Labels: bug

#116 deploy 수수수수수수수정 (jar 방식으로 변경 후 working directory 지정)
  .github/workflows/deploy.yml
Labels: bug

#124 hotfix - deploy 수정수정
  .github/workflows/deploy.yml
Labels: bug

#125 hotfix - depoloy 수정 이건 진짜 된다
  .github/workflows/deploy.yml
Labels: bug

#128 hotfix 무조건 무조건 된다 된다
  .github/workflows/deploy.yml
Labels: bug

#145 feat(chat): 채팅방 기능 및 포메이션, 점수계산 로직 변경(#78)
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/RosterResponse.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/ScoreboardItem.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatRoomQueryServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/repository/ParticipantPlayerRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/match/repository/ParticipantRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/entity/Player.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/repository/PlayerFixtureStatRepository.java
Labels: enhancement

#146 배포 백엔드로직 수정(채팅방 기능 및 포메이션, 점수계산 로직 변경)
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/RosterResponse.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/dto/ScoreboardItem.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatRoomQueryServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/repository/ParticipantPlayerRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/match/repository/ParticipantRepository.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/entity/Player.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/repository/PlayerFixtureStatRepository.java
Labels: enhancement

#148 feat(chat): 채팅방 채팅 메세지 전달 로직 변경 (#78)
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisPublisher.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisSubscriber.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatMessagingController.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/UnifiedWebSocketConfig.java
Labels: enhancement

#149 [Feat] 채팅 메세지 전달 경로 변경
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisPublisher.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisSubscriber.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatMessagingController.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/UnifiedWebSocketConfig.java
Labels: enhancement

#174 feat(Document): 스웨거 정리 및 스웨거 페이지별 그룹 처리(#78)
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisPublisher.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisSubscriber.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/RedisPubSubConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatHistoryController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatMessagingController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatNotificationController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatReadController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatRoomQueryController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/ChatReindexController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/controller/ChatSearchController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatNotificationServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/controller/DraftController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/cache/controller/PlayerCacheController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/elasticsearch/controller/PlayerEsController.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/OpenApiConfig.java
Labels: documentation, enhancement

#175 [Documnet] 스웨거 정리 및 스웨거 페이지별 그룹 처리(#78)
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisPublisher.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/ChatRedisSubscriber.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/bus/RedisPubSubConfig.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatHistoryController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatMessagingController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatNotificationController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatReadController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/controller/ChatRoomQueryController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/ChatReindexController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/elasticsearch/controller/ChatSearchController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/chat/service/Impl/ChatNotificationServiceImpl.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/draft/controller/DraftController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/cache/controller/PlayerCacheController.java
  backendProject/src/main/java/likelion/mlb/backendProject/domain/player/elasticsearch/controller/PlayerEsController.java
  backendProject/src/main/java/likelion/mlb/backendProject/global/configuration/OpenApiConfig.java
Labels: documentation
